version: "3.8"
services:
  printer:
    container_name: printer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./printer_storage/webcam_images:/home/printer/webcam_images
      - ./printer_storage/timelapse:/home/printer/timelapse
      - ./printer_storage/printer_data:/home/printer/printer_data:rw
    ports:
      - "7125:7125"
      - "8110:8080"
    networks:
      - dev_net
networks:
  dev_net:
    driver: bridge
